# Generated by Django 4.2.1 on 2023-05-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=150)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
